# Generated by Django 4.0 on 2022-03-11 14:58

import consumer_profile.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provience', models.CharField(blank=True, choices=[('Provience No.1', 'Provience No 1'), ('Provience No.2', 'Provience No 2'), ('Provience No.3', 'Provience No 3'), ('Gandaki Pradesh', 'Gandaki Pradesh'), ('Provience No.5', 'Provience No 5'), ('Karnali Pradesh', 'Karnali Pradesh'), ('Sudurpashchim Pradesh', 'Sudurpashchim Pradesh')], default='Provience No.3', max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[consumer_profile.models.validate_mobile])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('response', models.CharField(max_length=100)),
                ('review_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_profile.userprofile')),
            ],
        ),
    ]
