# Generated by Django 4.0 on 2022-03-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('consumer_profile', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount'),
        ),
    ]
