# Generated by Django 4.0 on 2022-03-18 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_profile', '0005_alter_reviews_rating_alter_reviews_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='response',
            field=models.CharField(max_length=100),
        ),
    ]
