# Generated by Django 4.0 on 2022-03-18 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_profile', '0006_alter_reviews_rating_alter_reviews_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='response',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
